- name: pull sources from github
  git: >
    repo={{silversearcher_ag_repo}}
    dest={{silversearcher_ag_sources_path}}
    update=yes
  register: gitrepo


- name: compile and install
  shell: "{{item}}"
  args:
    chdir: "{{silversearcher_ag_sources_path}}"
  become: yes
  with_items:
    - "./build.sh"
    - "make install"
  when: gitrepo.changed
